/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pages.componentes;

/**
 *
 * @author victo
 */
public class Fechar extends javax.swing.JPanel {

    /**
     * Creates new form Fechar
     */
    public Fechar(int r,int g,int b, int r1, int g1, int b1) {
        initComponents(r,g,b,r1,g1,b1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(int r,int g,int b, int r1, int g1, int b1) {

        sair = new javax.swing.JLabel();
        sair.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sair.setForeground(new java.awt.Color(r,g,b));
        setBackground(new java.awt.Color(r1,g1,b1));
        sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sair.setText("x");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
       
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sair)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel sair;
    // End of variables declaration//GEN-END:variables
}
