package pages.componentes;

import javax.swing.SwingUtilities;

import pages.*;
import pages.SelecaoPix;


public class FuncaoHome extends javax.swing.JPanel {

   
    public FuncaoHome(String nome, String nomeIcone) {
        initComponents(nome, nomeIcone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String nome, String nomeIcone) {

        ted = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        ted.setBackground(new java.awt.Color(255, 255, 255));
        ted.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 188, 187), 2, true));
        ted.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/"+nomeIcone))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(nome);

        this.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setTela(evt,nome);
            }
        });
       

        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        javax.swing.GroupLayout tedLayout = new javax.swing.GroupLayout(ted);
        ted.setLayout(tedLayout);
        tedLayout.setHorizontalGroup(
            tedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        tedLayout.setVerticalGroup(
            tedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tedLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setTela(java.awt.event.MouseEvent evt, String nome) {//GEN-FIRST:event_criarContaMouseClicked
       switch(nome){
        case "Ted":
            Ted ted = new Ted();
            SwingUtilities.getWindowAncestor(this).dispose();
            ted.setVisible(true);
           break;
        case "Pix":
            SelecaoPix pix = new SelecaoPix();
            SwingUtilities.getWindowAncestor(this).dispose();
            pix.setVisible(true);
            break;
        case "Saque":
            Saque saque = new Saque();
            SwingUtilities.getWindowAncestor(this).dispose();
            saque.setVisible(true);
            break;
        
        case "Deposito":
            Deposito deposito = new Deposito();
            SwingUtilities.getWindowAncestor(this).dispose();
            deposito.setVisible(true);
            break;
        default:
            Home k = new Home();
            SwingUtilities.getWindowAncestor(this).dispose();
            k.setVisible(true);
            break;

       }
    
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel ted;
    // End of variables declaration//GEN-END:variables
}
