/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pages.componentes;

/**
 *
 * @author victo
 */
public class InputSenha extends javax.swing.JPanel {

    /**
     * Creates new form Input
     */
    public InputSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTexto = new javax.swing.JLabel();
        linhaNumConta = new javax.swing.JSeparator();
        inputNumConta = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        nomeTexto.setBackground(new java.awt.Color(255, 255, 255));
        nomeTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        nomeTexto.setText("Senha");

        linhaNumConta.setForeground(new java.awt.Color(0, 0, 0));

        inputNumConta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputNumConta.setBorder(null);
        inputNumConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(linhaNumConta)
                    .addComponent(inputNumConta)
                    .addComponent(nomeTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nomeTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(linhaNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputNumContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputNumConta;
    private javax.swing.JSeparator linhaNumConta;
    private javax.swing.JLabel nomeTexto;
    // End of variables declaration//GEN-END:variables
}
