/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pages.componentes;

import javax.swing.SwingUtilities;

import pages.Login;

/**
 *
 * @author victo
 */
public class MenuLateral extends javax.swing.JPanel {

    /**
     * Creates new form menuLateral
     */
    public MenuLateral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuEsq = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        agencia = new javax.swing.JLabel();
        numConta = new javax.swing.JLabel();
        sair = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(297, 570));
        setPreferredSize(new java.awt.Dimension(287, 570));
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });


        menuEsq.setBackground(new java.awt.Color(34, 180, 167));

        nome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome.setText("Victor Chagas");

        icone.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 255, 255));
        icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/userMenor.png"))); // NOI18N

        agencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        agencia.setForeground(new java.awt.Color(255, 255, 255));
        agencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agencia.setText("8080-X");

        numConta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numConta.setForeground(new java.awt.Color(255, 255, 255));
        numConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numConta.setText("01929494-8");

        sair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sair.setForeground(new java.awt.Color(255, 255, 255));
        sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sair (1).png"))); // NOI18N
        sair.setText("Sair");
        sair.setMaximumSize(new java.awt.Dimension(100, 100));
        sair.setPreferredSize(new java.awt.Dimension(343, 256));

        javax.swing.GroupLayout menuEsqLayout = new javax.swing.GroupLayout(menuEsq);
        menuEsq.setLayout(menuEsqLayout);
        menuEsqLayout.setHorizontalGroup(
            menuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuEsqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuEsqLayout.createSequentialGroup()
                        .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(menuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEsqLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(numConta, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        menuEsqLayout.setVerticalGroup(
            menuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEsqLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(icone)
                .addGap(18, 18, 18)
                .addComponent(nome)
                .addGap(63, 63, 63)
                .addComponent(agencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(menuEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEsqLayout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(numConta)
                    .addContainerGap(328, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuEsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuEsq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    
    private void sairMouseClicked(java.awt.event.MouseEvent evt) {                                  
        Login login = new Login();
        SwingUtilities.getWindowAncestor(this).dispose();
        login.setVisible(true);
    }                                 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agencia;
    private javax.swing.JLabel icone;
    private javax.swing.JPanel menuEsq;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numConta;
    private javax.swing.JLabel sair;
    // End of variables declaration//GEN-END:variables
}
