/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pages.componentes;

import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import pages.*;


/**
 *
 * @author victo
 */
public class TelaFuncional extends javax.swing.JPanel {

    public TelaFuncional(String nome, String icone, String nomeBotao,String descricao) {
        initComponents(nome,icone,nomeBotao,descricao);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents(String nome, String icone, String nomeBotao,String descricao) {

        telaTotal = new javax.swing.JPanel();
        JPanel tituloFuncao = new TituloFuncao(nome, icone);
        voltar = new javax.swing.JLabel();
        textoTransferencia = new javax.swing.JLabel();
        inputValor = new javax.swing.JTextField();
        JPanel botaoTransferencia = new BotaoFuncao(nomeBotao);


        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltar(evt,nome);
            }
        });
       

        telaTotal.setBackground(new java.awt.Color(255, 255, 255));

        inputValor.setBorder(BorderFactory.createCompoundBorder(
        inputValor.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        inputValor.setFont(new java.awt.Font("Segoe UI", 1, 30));

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/voltarV.png"))); // NOI18N

        textoTransferencia.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        textoTransferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTransferencia.setText(descricao);       

        javax.swing.GroupLayout telaTotalLayout = new javax.swing.GroupLayout(telaTotal);
        telaTotal.setLayout(telaTotalLayout);
        telaTotalLayout.setHorizontalGroup(
            telaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaTotalLayout.createSequentialGroup()
                .addGroup(telaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaTotalLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(voltar))
                    .addGroup(telaTotalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(telaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(telaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tituloFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputValor)))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        telaTotalLayout.setVerticalGroup(
            telaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltar)
                .addGap(4, 4, 4)
                .addComponent(tituloFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoTransferencia)
                .addGap(44, 44, 44)
                .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(botaoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telaTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(telaTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //GEN-LAST:event_botaoTransferenciaActionPerformed
    private void voltar(java.awt.event.MouseEvent evt,String nome) {//GEN-FIRST:event_criarContaMouseClicked
            switch(nome){
                case "PIX":
                    SelecaoPix pix = new SelecaoPix();
                    SwingUtilities.getWindowAncestor(this).dispose();
                    pix.setVisible(true);
                    break;
                default:
                    Home home = new Home();
                    SwingUtilities.getWindowAncestor(this).dispose();
                    home.setVisible(true);
            }
        }
    private javax.swing.JTextField inputValor;
    private javax.swing.JPanel telaTotal;
    private javax.swing.JLabel textoTransferencia;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
