/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;
import pages.componentes.*;
import javax.swing.JPanel;
import logic.Pix;

/**
 *
 * @author victo
 */
public class Login extends javax.swing.JFrame {
    
    /**
     * Creates new form PrincipalTela
     */
    public Login() {
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JPanel numConta = new Input("Numero da conta", "user.png");
        JPanel senha = new InputSenha();

        telaBoasVindas = new javax.swing.JPanel();
        iconeBanco = new javax.swing.JLabel();
        textoBanco = new javax.swing.JLabel();
        textoBemvindoBanco = new javax.swing.JLabel();
        painelLogin = new javax.swing.JPanel();
        sair = new javax.swing.JLabel();
        tituloLogin = new javax.swing.JLabel();
        textoBoasvindasLogin = new javax.swing.JLabel();
        naoConta = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();
        criarConta = new javax.swing.JLabel();
    

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        telaBoasVindas.setBackground(new java.awt.Color(34, 180, 167));

        iconeBanco.setBackground(new java.awt.Color(23, 159, 211));
        iconeBanco.setForeground(new java.awt.Color(255, 255, 255));
        iconeBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bank.png"))); // NOI18N

        textoBanco.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoBanco.setForeground(new java.awt.Color(255, 255, 255));
        textoBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBanco.setText("Sistema Bancario");

        textoBemvindoBanco.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoBemvindoBanco.setForeground(new java.awt.Color(255, 255, 255));
        textoBemvindoBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBemvindoBanco.setText(" Bem vindo!");

        javax.swing.GroupLayout telaBoasVindasLayout = new javax.swing.GroupLayout(telaBoasVindas);
        telaBoasVindas.setLayout(telaBoasVindasLayout);
        telaBoasVindasLayout.setHorizontalGroup(
            telaBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaBoasVindasLayout.createSequentialGroup()
                .addGroup(telaBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaBoasVindasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(textoBanco, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaBoasVindasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconeBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(telaBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(telaBoasVindasLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(textoBemvindoBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        telaBoasVindasLayout.setVerticalGroup(
            telaBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaBoasVindasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(telaBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(telaBoasVindasLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(textoBemvindoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));

        sair.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sair.setForeground(new java.awt.Color(34, 180, 167));
        sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sair.setText("x");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });

        tituloLogin.setBackground(new java.awt.Color(34, 180, 167));
        tituloLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloLogin.setForeground(new java.awt.Color(34, 180, 167));
        tituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLogin.setText("Login");
        tituloLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        textoBoasvindasLogin.setBackground(new java.awt.Color(34, 180, 167));
        textoBoasvindasLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoBoasvindasLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBoasvindasLogin.setText("Bem vindo ao sistema");
        textoBoasvindasLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        naoConta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        naoConta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        naoConta.setText("Nao tem uma conta?");

        entrar.setBackground(new java.awt.Color(34, 180, 167));
        entrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("Entrar");
        entrar.setBorderPainted(false);
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar.setFocusPainted(false);
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        criarConta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        criarConta.setText("Crie aqui");
        criarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        criarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarContaMouseClicked(evt);
            }
        });

    

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoBoasvindasLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(naoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(criarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tituloLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoBoasvindasLogin)
                .addGap(26, 26, 26)
                .addComponent(numConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(entrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaBoasVindas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaBoasVindas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(926, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarActionPerformed

    private void inputNumContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumContaActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        this.dispose();
    }//GEN-LAST:event_sairMouseClicked

    private void criarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarContaMouseClicked
        TipoPessoa tipoPessoa = new TipoPessoa();
    
        this.dispose();
        tipoPessoa.setVisible(true);
    }//GEN-LAST:event_criarContaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel criarConta;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel iconeBanco;
    private javax.swing.JLabel naoConta;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JLabel sair;
    private javax.swing.JPanel telaBoasVindas;
    private javax.swing.JLabel textoBanco;
    private javax.swing.JLabel textoBemvindoBanco;
    private javax.swing.JLabel textoBoasvindasLogin;
    private javax.swing.JLabel tituloLogin;
    // End of variables declaration//GEN-END:variables
}
